# Generated by Django 4.1.1 on 2022-09-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
