# Generated by Django 4.1.1 on 2022-10-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_headuseraccess_church_headuseraccess_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headuseraccess',
            name='church',
        ),
        migrations.RemoveField(
            model_name='headuseraccess',
            name='description',
        ),
        migrations.RemoveField(
            model_name='headuseraccess',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='headuseraccess',
            name='name',
        ),
        migrations.RemoveField(
            model_name='headuseraccess',
            name='role',
        ),
        migrations.RemoveField(
            model_name='headuseraccess',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='headuseraccess',
            name='video',
        ),
    ]
