# Generated by Django 4.1.1 on 2022-10-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_church'),
        ('account', '0004_headuseraccess_church_headuseraccess_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headuseraccess',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='church.church'),
        ),
        migrations.AlterField(
            model_name='headuseraccess',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='headuseraccess',
            name='foto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='headuseraccess',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='headuseraccess',
            name='role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='headuseraccess',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='headuseraccess',
            name='video',
            field=models.CharField(max_length=255),
        ),
    ]
