# Generated by Django 4.1.1 on 2022-09-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
