# Generated by Django 4.1.1 on 2022-09-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
