# Generated by Django 4.1.1 on 2022-09-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_headuseraccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeadUserAccess',
        ),
    ]
