# Generated by Django 4.1.1 on 2022-10-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_delete_headuseraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
