# Generated by Django 4.1.1 on 2022-10-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('head', models.CharField(max_length=50)),
                ('chat', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
